### ISSUE TITLE
Resolve by container name

### ISSUE THREAD

**Issue by MichaelSp** [iverberk/docker-spy#5]
Wouldn't it be nice to also resolve the container by its name?
I'm not a go-pro, so unfortunately I can't hack it myself...

**Comment by iverberk** [comment]
What would be the benefit? The container name and hostname are both specified from the commandline (or fig/crane config). What would be your use-case for this?

**Comment by MichaelSp** [comment]
Oh, I didn't know about the "--hostname=" option. Good point.
